#mysql?????
spring:
  datasource:
    url: jdbc:mysql://58.87.96.86:3306/student_inquire     # database?????????
    username: root                                         # root????????
    password: Ccjy88007886                                 # password????????
    driver-class-name: com.mysql.cj.jdbc.Driver

